from enum import Enum

class Motivo_Cliente(Enum):
    COMPRAR_ACCESORIOS ="COMPRAR_ACCESORIOS"
    ENTREGAR_BICICLETA_REPARACION = "ENTREGAR_BICICLETA_REPARACION"
    RETIRAR_BICICLETA_REPARADA = "RETIRAR_BICICLETA_REPARADA"
